In [1]:
import pandas as pd

In [7]:
food_info = pd.read_csv("food_info.csv")
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,157.0,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,5.0,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,100.0,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,100.0,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0

In [4]:
print(type(food_info))

<class 'pandas.core.frame.DataFrame'>

In [6]:
row_100 = food_info.loc[99]
row_100

NDB_No                                  1111
Shrt_Desc          MILK SHAKES THICK VANILLA
Water_(g)                              74.45
Energ_Kcal                               112
Protein_(g)                             3.86
Lipid_Tot_(g)                           3.03
Ash_(g)                                 0.91
Carbohydrt_(g)                         17.75
Fiber_TD_(g)                               0
Sugar_Tot_(g)                          17.75
Calcium_(mg)                             146
Iron_(mg)                                0.1
Magnesium_(mg)                            12
Phosphorus_(mg)                          115
Potassium_(mg)                           183
Sodium_(mg)                               95
Zinc_(mg)                               0.39
Copper_(mg)                            0.051
Manganese_(mg)                         0.014
Selenium_(mcg)                           2.3
Vit_C_(mg)                                 0
Thiamin_(mg)                            0.03
Riboflavin_(mg)                        0.195
Niacin_(mg)                            0.146
Vit_B6_(mg)                            0.042
Vit_B12_(mcg)                           0.52
Vit_A_IU                                  91
Vit_A_RAE                                 25
Vit_E_(mg)                              0.05
Vit_D_mcg                                1.2
Vit_D_IU                                  48
Vit_K_(mcg)                              0.2
FA_Sat_(g)                             1.886
FA_Mono_(g)                            0.875
FA_Poly_(g)                            0.113
Cholestrl_(mg)                            12
Name: 99, dtype: object

In [15]:
index_last_rows = (food_info.shape[0]) - 5

last_five_rows = food_info.loc[index_last_rows:]
last_five_rows

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.0,...,157.0,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.0,...,5.0,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.2,...,0.0,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.0,...,100.0,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.0,...,100.0,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0

In [16]:
protein = food_info["Protein_(g)"]
cholesterol = food_info["Cholestrl_(mg)"]

In [17]:
protein

0        0.85
1        0.85
2        0.28
3       21.40
4       23.24
        ...
8613    18.50
8614    20.54
8615     0.00
8616    16.10
8617    19.80
Name: Protein_(g), Length: 8618, dtype: float64

In [18]:
cholesterol

0       215.0
1       219.0
2       256.0
3        75.0
4        94.0
        ...
8613     95.0
8614     41.0
8615      0.0
8616     50.0
8617     50.0
Name: Cholestrl_(mg), Length: 8618, dtype: float64

In [20]:
food_info.columns.values

array(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)',
       'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)',
       'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)'], dtype=object)

In [21]:
selenium_thiamin = food_info[["Shrt_Desc", "Shrt_Desc", 'Thiamin_(mg)']]
selenium_thiamin

                       Shrt_Desc                   Shrt_Desc  Thiamin_(mg)
0               BUTTER WITH SALT            BUTTER WITH SALT         0.005
1       BUTTER WHIPPED WITH SALT    BUTTER WHIPPED WITH SALT         0.005
2           BUTTER OIL ANHYDROUS        BUTTER OIL ANHYDROUS         0.001
3                    CHEESE BLUE                 CHEESE BLUE         0.029
4                   CHEESE BRICK                CHEESE BRICK         0.014
...                          ...                         ...           ...
8613             MACKEREL SALTED             MACKEREL SALTED         0.020
8614  SCALLOP (BAY&SEA) CKD STMD  SCALLOP (BAY&SEA) CKD STMD         0.012
8615                  SYRUP CANE                  SYRUP CANE         0.130
8616                   SNAIL RAW                   SNAIL RAW         0.010
8617            TURTLE GREEN RAW            TURTLE GREEN RAW         0.120

[8618 rows x 3 columns]

Select all columns with units gramm

In [23]:
columns_name = food_info.columns.values
columns_name

array(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)',
       'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)',
       'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)'], dtype=object)

In [30]:
columns_name = list(columns_name)
columns_name

['NDB_No',
 'Shrt_Desc',
 'Water_(g)',
 'Energ_Kcal',
 'Protein_(g)',
 'Lipid_Tot_(g)',
 'Ash_(g)',
 'Carbohydrt_(g)',
 'Fiber_TD_(g)',
 'Sugar_Tot_(g)',
 'Calcium_(mg)',
 'Iron_(mg)',
 'Magnesium_(mg)',
 'Phosphorus_(mg)',
 'Potassium_(mg)',
 'Sodium_(mg)',
 'Zinc_(mg)',
 'Copper_(mg)',
 'Manganese_(mg)',
 'Selenium_(mcg)',
 'Vit_C_(mg)',
 'Thiamin_(mg)',
 'Riboflavin_(mg)',
 'Niacin_(mg)',
 'Vit_B6_(mg)',
 'Vit_B12_(mcg)',
 'Vit_A_IU',
 'Vit_A_RAE',
 'Vit_E_(mg)',
 'Vit_D_mcg',
 'Vit_D_IU',
 'Vit_K_(mcg)',
 'FA_Sat_(g)',
 'FA_Mono_(g)',
 'FA_Poly_(g)',
 'Cholestrl_(mg)']

In [32]:
gram_columns = []

for i in columns_name:
    if i.endswith("(g)"):
        gram_columns.append(i)

gram_columns

['Water_(g)',
 'Protein_(g)',
 'Lipid_Tot_(g)',
 'Ash_(g)',
 'Carbohydrt_(g)',
 'Fiber_TD_(g)',
 'Sugar_Tot_(g)',
 'FA_Sat_(g)',
 'FA_Mono_(g)',
 'FA_Poly_(g)']

In [34]:
df_gram = food_info[gram_columns]
df_gram

,Water_(g),Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g)
0,15.87,0.85,81.11,2.11,0.06,0.0,0.06,51.368,21.021,3.043
1,15.87,0.85,81.11,2.11,0.06,0.0,0.06,50.489,23.426,3.012
2,0.24,0.28,99.48,0.00,0.00,0.0,0.00,61.924,28.732,3.694
3,42.41,21.40,28.74,5.11,2.34,0.0,0.50,18.669,7.778,0.800
4,41.11,23.24,29.68,3.18,2.79,0.0,0.51,18.764,8.598,0.784
...,...,...,...,...,...,...,...,...,...,...
8613,43.00,18.50,25.10,13.40,0.00,0.0,0.00,7.148,8.320,6.210
8614,70.25,20.54,0.84,2.97,5.41,0.0,0.00,0.218,0.082,0.222
8615,26.00,0.00,0.00,0.86,73.14,0.0,73.20,0.000,0.000,0.000
8616,79.20,16.10,1.40,1.30,2.00,0.0,0.00,0.361,0.259,0.252
8617,78.50,19.80,0.50,1.20,0.00,0.0,0.00,0.127,0.088,0.170

In [35]:
sodium_gram = food_info["Sodium_(mg)"] / 1000
sodium_gram

0       0.643
1       0.659
2       0.002
3       1.146
4       0.560
        ...
8613    4.450
8614    0.667
8615    0.058
8616    0.070
8617    0.068
Name: Sodium_(mg), Length: 8618, dtype: float64

In [37]:
sugar_milligram = food_info["Sugar_Tot_(g)"] * 1000
sugar_milligram

0          60.0
1          60.0
2           0.0
3         500.0
4         510.0
         ...
8613        0.0
8614        0.0
8615    73200.0
8616        0.0
8617        0.0
Name: Sugar_Tot_(g), Length: 8618, dtype: float64

In [38]:
food_info.columns.values

array(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)',
       'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)',
       'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)'], dtype=object)

In [39]:
gram_of_protein_per_gram_of_water = food_info["Protein_(g)"] / food_info["Water_(g)"]
milligrams_of_calcium_and_iron = food_info["Calcium_(mg)"] + food_info["Iron_(mg)"]

In [40]:
gram_of_protein_per_gram_of_water.head()

0    0.053560
1    0.053560
2    1.166667
3    0.504598
4    0.565313
dtype: float64

In [41]:
milligrams_of_calcium_and_iron.head()

0     24.02
1     24.16
2      4.00
3    528.31
4    674.43
dtype: float64

In [44]:
protein = food_info["Protein_(g)"] * 2
fat = food_info["Lipid_Tot_(g)"] * (- 0.75)

In [45]:
rating = protein + fat
rating

0      -59.1325
1      -59.1325
2      -74.0500
3       21.2450
4       24.2200
         ...
8613    18.1750
8614    40.4500
8615     0.0000
8616    31.1500
8617    39.2250
Length: 8618, dtype: float64

In [53]:
normalized_protein = food_info["Protein_(g)"] / (food_info["Protein_(g)"].max())
normalized_lipid = food_info["Lipid_Tot_(g)"] / (food_info["Lipid_Tot_(g)"].max())

In [54]:
normalized_protein

0       0.009624
1       0.009624
2       0.003170
3       0.242301
4       0.263134
          ...
8613    0.209466
8614    0.232563
8615    0.000000
8616    0.182292
8617    0.224185
Name: Protein_(g), Length: 8618, dtype: float64

In [56]:
normalized_lipid

0       0.8111
1       0.8111
2       0.9948
3       0.2874
4       0.2968
         ...
8613    0.2510
8614    0.0084
8615    0.0000
8616    0.0140
8617    0.0050
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

In [62]:
food_info = pd.read_csv("food_info.csv")

In [69]:
food_info["Normalized_protein"] = normalized_protein
food_info["Normalized_fat"] = normalized_lipid

In [70]:
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_protein,Normalized_fat,Norm_nutr_index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.009624,0.8111,0.012030
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.009624,0.8111,0.012030
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.003170,0.9948,0.003963
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.242301,0.2874,0.302876
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.263134,0.2968,0.328918

In [73]:
food_info["Norm_nutr_index"] = (food_info["Normalized_protein"] * 2)   + ((-0.75) * food_info["Normalized_fat"])
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_protein,Normalized_fat,Norm_nutr_index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.009624,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.009624,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.003170,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.242301,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.263134,0.2968,0.303668

In [77]:
food_info.sort_values("Norm_nutr_index", inplace=True, ascending=False)
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_protein,Normalized_fat,Norm_nutr_index
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.0,0.0,0.0,0.066,0.101,0.258,0.0,1.000000,0.0053,1.996025
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.0,0.0,0.0,0.070,0.060,0.010,0.0,0.969203,0.0010,1.937656
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.0,0.0,0.0,0.147,0.173,0.070,20.0,0.958220,0.0048,1.912840
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.932971,0.0004,1.865642
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,NaN,NaN,NaN,0.600,1.330,0.370,NaN,0.935236,0.0230,1.853221